### ISSUE TITLE
Holding : expected date should be today's date by default

### ISSUE THREAD

**Issue by JoelleDosimont** [rero/rero-ils#1249] opened 2020-09-30 08:53 UTC
In the professional interface, when adding a new serial holding, the expected date is empty.
--> The expected date should be today's date by default, as the serial holding is usually created at the reception of the "first" number.

**Comment by pronguen** [comment] 2020-10-13 07:58
Duplicate of #1290

**Closed by pronguen** 2020-10-13 07:58 UTC
Labels: enhancement, triage
