### ISSUE TITLE
Placeholder in patron form

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#804] opened 2020-02-25 15:28 UTC
**Describe the issue**
For two fields, a specific syntax is expected but the user doesn't know it before receiving the validation message.

**To Reproduce**
1. Click to add a new patron
1. Enter a value in fields `phone` and `birth_date`
1. See validation message

**Expected behavior**
A placeholder announces how the value should be entered, in accordance with our [UX charter](https://github.com/rero/rero-ils/wiki/UX-charter#placeholder)
- birth_date: "Example: 1985-12-29"
- phone: "Example: +41791231212"

**Software version**
ilsdev
rero-ils version 854c0fe
rero-ils-ui version a8e8f2fc

**Comment by AoNoOokami** [comment] 2020-02-28 07:03
Duplicate of https://github.com/rero/rero-ils/issues/538 I think

**Closed** 2020-04-10 15:10 UTC
Labels: minor
