### ISSUE TITLE
serials: enumeration and chronology field is incorrect in the slow issue receive

### ISSUE THREAD

**Issue by BadrAly** [rero/rero-ils#1696] opened 2021-02-11 17:11 UTC
From the holdings detail view, librarian has two ways to receive the next issue:
1. quick (no editing)
2. slow (possibility to edit the issue before receiving)

If a librarian decides to use the slow receive, the Enumeration and chronology proposed in the issue editor is for the last received issue. It should be the Enumeration and chronology for the next issue.

* server: [ils.test.rero.ch][1]
* version: `v.1.0.0` 

<img width="1638" alt="Screenshot 2021-02-11 at 18 11 11" src="https://user-images.githubusercontent.com/26998238/107671813-8bb84100-6c94-11eb-8d0a-c97418ce30e8.png">

The Enumeration and chronology is "Vol 2012" in the editor instead of "Vol 2013"

<img width="1238" alt="Screenshot 2021-02-11 at 18 10 54" src="https://user-images.githubusercontent.com/26998238/107671775-7d6a2500-6c94-11eb-8191-6d4375ecd816.png">

[1]: https://ils.test.rero.ch

**Comment by BadrAly** [comment] 2021-02-11 17:41
@zannkukai after a quick analysis: A quick fix is to use the `holdings.receive_regular_issue` api for the `slow` receive instead of the `item.update`

**Comment by zannkukai** [comment] 2021-02-12 09:25
@BadrAly for a 'slow' receive we use the holding ng-core editor based on jsonschema, we provide some arguments to the editor using the query string URL. So first, I can't change the behavior of the holding form submit. 

Why we need to know is : why the prediction isn't well updated when the issue is created.

**Comment by zannkukai** [comment] 2021-02-12 09:39
I just reproduce the problem with `https://ils.test.rero.ch/professional/records/holdings/detail/968`.
All seems right with data (https://ils.test.rero.ch/api/holdings/968 and https://ils.test.rero.ch/api/items/1664)

* When an item is created, then this method is called : https://github.com/rero/rero-ils/blob/dev/rero_ils/modules/items/api/record.py#L100
* According to data (https://ils.test.rero.ch/api/holdings/968 and https://ils.test.rero.ch/api/items/1664) all checks from https://github.com/rero/rero-ils/blob/7894bebf1edb10a69246e99c26b9da2ca0234b9a/rero_ils/modules/items/api/record.py#L152 should be valid. So the https://github.com/rero/rero-ils/blob/7894bebf1edb10a69246e99c26b9da2ca0234b9a/rero_ils/modules/items/api/record.py#L156 should be called.

**Comment by zannkukai** [comment] 2021-02-12 11:02
Ok, all seems working fine in backend :: 
  * The prevision is well updated
  * we called `holding.update()` with correct data

But, we called the `update` with the same `dbcommit, reindex` arguments than from `Item.create()` method (False by default). So the change isn't dbcommited using the db session was commited. 
This is committed by "invenio_record_rest" (https://github.com/inveniosoftware/invenio-records-rest/blob/master/invenio_records_rest/views.py#L697) But this call, commit changes on Item, not on the holding.

A quick and dirty solution should be to force `True` for the call to `holding.update()` (https://github.com/rero/rero-ils/blob/dev/rero_ils/modules/items/api/record.py#L158

**Closed** 2021-02-25 10:06 UTC
Labels: P: Medium, bug, professional ui, serials
