### ISSUE TITLE
Summary not displayed after clicking on 'show more'

### ISSUE THREAD

**Issue by ManaDeweerdt** [rero/rero-ils#2551] opened 2021-11-24 08:11 UTC
**Describe the bug**

Sometimes on the public interface, the summary disappears after clicking on 'show more'.

**To Reproduce**

This one disappears Ex Naked Came the Florida Man https://ils.test.rero.ch/global/documents/2005774
This one works  Ex https://ilsdev.test.rero.ch/aoste/documents/2006025
This one also works Ex https://ils.test.rero.ch/aoste/documents/2003551

**Expected behavior**

The summary should be displayed after expanding with the button 'show more'.

**Context**

* server: [ils.test.rero.ch][1] or [ilsdev.test.rero.ch][2]?
* version: `v1.6.1` or the commit hash (see frontpage).
* browser: [if relevant, e.g. chrome, safari, version 78].

[1]: https://ils.test.rero.ch
[2]: https://ilsdev.test.rero.ch

**Screenshots**

**Additional context**

related to https://github.com/rero/rero-ils/issues/2691

**Comment by ManaDeweerdt** [comment] 2021-12-17 13:53
The issue seems to be resolved in the 1.7.0

**Comment by pronguen** [comment] 2022-01-24 10:53
It is not completely solved. See this example:
https://bib.rero.ch/rbnj/documents/976856

**Comment by pronguen** [comment] 2022-01-24 10:54
I open another issue since it's a different problem. Sorry.

**Comment by PascalRepond** [comment] 2022-02-11 10:54
Duplicate of https://github.com/rero/rero-ils/issues/2691

**Closed** 2022-03-14 14:44 UTC
Labels: duplicate, f: public ui, bug, p-Low
