### ISSUE TITLE
Circulation policy custom editor do not load patron types and item types settings

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#625] opened 2019-11-13 18:09 UTC
**Describe the issue**
When I save a circulation policy, the settings part is saved (check via API). But if I reopen it, the changes don't appear, even after reloading the page. What is more, I can create another policy with the same settings and save if without restriction.

**To Reproduce**
1. Create a new policy
1. Make your policy apply to specific patron and item types
1. Save
1. Reopen the policy
1. See error: changes you made were not saved (ie the selection of patron and item types), even if you reload the page
1. Create another policy applying to the same patron and item types
1. Save it

**Expected behavior**
* When reopening the policy for edition, changes are displayed without page reload.
* It is not possible to select settings already concerned by another policy.

**Software version**
Tested on 
* ilsdev.test, version 1de3d25e
* ils.testversion 0.5.2

**Comment by iGormilhit** [comment] 2019-11-14 06:32
I cannot reproduce the issue on ilsdev. I will try again.

**Comment by iGormilhit** [comment] 2019-11-14 07:21
I got it, it's the changes on which patron type and item types that this circulation policy is applied to, that are not displayed in the editor. The changes are commited to the database though.

**Comment by iGormilhit** [comment] 2019-11-21 09:39
Should be fixed by PR https://github.com/rero/rero-ils/pull/633, commit https://github.com/rero/rero-ils/pull/633/commits/797ee0caf751ddb28f1b76d2cc1786914d66c726.

**Comment by AoNoOokami** [comment] 2019-11-22 07:32
> Should be fixed by PR #633, commit [797ee0c](https://github.com/rero/rero-ils/commit/797ee0caf751ddb28f1b76d2cc1786914d66c726).

I tried to create a circulation policy in PR #633 context, but when I click on save button, I get this error:
`ERROR TypeError: settings[key].forEach is not a function`

**Closed** 2020-02-26 17:59 UTC
Labels: bug, custom editor, professional ui
