### ISSUE TITLE
Removing existing user role can lead to unintended issues.

### ISSUE THREAD

**Issue by iGormilhit** [rero/rero-ils#1438] opened 2020-11-12 07:21 UTC
**Describe the bug**
Removing an existing role of a user can lead to unintended issues.

**To Reproduce**
1. Go to the professional interface
2. Find a patron **that has subscription* and edit it.
3. Remove its patron role and add the librarian role.
4. Complete the form accordingly.
5. Try to save and see that the spinner never ends.

**Expected behavior**
The expected behavior is certainly that you cannot remove existing role without further controls: are subscriptions, fees, loans attached to this patron? Is this user the last existing system librarian of an organisation?

**Context**

* server: [ilsdev.test.rero.ch][1]
* version (US patron without email):
    * rero-ils version [2ad75f82][2]
    * rero-ils-ui version [a080c438][3]

[1]: https://ilsdev.test.rero.ch
[2]: https://github.com/rero/rero-ils/commit/2ad75f82a1cf64b4dbdd1c0ae42a0ad99518854d
[3]: https://github.com/rero/rero-ils-ui/commit/a080c438d8e7a7e5e4ee7ba83268fff27206c2fa

**Comment by iGormilhit** [comment] 2020-12-16 11:46
Related to https://github.com/rero/rero-ils/issues/931.

**Comment by PascalRepond** [comment] 2023-01-30 15:23
Duplicate of #931

**Closed by PascalRepond** 2023-01-30 15:23 UTC
Labels: duplicate, f: user management, effort: important, bug, p-Medium
