### ISSUE TITLE
cataloging editor : contributor and subject fields : data deleted and duplicated

### ISSUE THREAD

**Issue by ThierryClavel** [rero/rero-ils#2625] opened 2022-01-03 13:28 UTC
**Describe the bug**

When adding a contributor or subject field by "duplicate button", an existing contributor is deleted and another is duplicated.

**To Reproduce**
exemple  https://bib.rero.ch/professional/records/documents/edit/2076666 :
I want to add  a new contributor between Martin, T. J and Chinn, Simon,I click on duplicate icon beside agent Martin, T.J. to add it..
Then one contributor (Chinn Simon) is deleted and another (Chinn Jonathan) is duplicated. 

**Expected behavior**

the new field is simply added 

* server: [bib.rero.ch] [bib..test.rero.ch]

* browser: Firefox

**Screenshots**

before adding field:
![image](https://user-images.githubusercontent.com/31695537/147935552-c5dc8087-062a-4436-a356-9ecd0c4d3759.png)

after field is added:
![image](https://user-images.githubusercontent.com/31695537/147935637-aa93288c-8783-4f75-85c7-78302e6c6a64.png)

**Comment by pronguen** [comment] 2022-03-14 07:51
I could not reproduce it on v1.9.0

**Comment by PascalRepond** [comment] 2022-03-14 07:55
I can reproduce. Issue is still present in v1.9.0. 
Firefox v98.0 (64bits) on Windows

**Comment by pronguen** [comment] 2022-03-14 08:02
@PascalRepond Could you give a document example and the way to reproduce it? Does the problem happen only with local contributors, with duplicating the last of the list, etc.?

**Comment by PascalRepond** [comment] 2022-03-14 08:09
Tried with this document : https://bib.test.rero.ch/professional/records/documents/edit/1780608
To reproduce: 
* add a contributor by clicking the duplicate button on any but the last two. 
* see that the existing GND and IdRef contributors displayed labels are not correct: the first one after the newly added one disappeared and the last one appears twice.

**Comment by PascalRepond** [comment] 2024-01-15 07:11
Might be fixed by ngx-formly v6?

**Closed** 2024-05-15 09:35 UTC
Labels: f: editor, bug, client request
