### ISSUE TITLE
Layout of confirmation message when deleting an item

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#407] opened 2019-07-18 12:08 UTC
When deleting an item, the message title should be on top left and no cross is needed, since there is a "cancel" button (see image below).

![image](https://user-images.githubusercontent.com/8154915/61455943-30618800-a965-11e9-8e32-07850bef2cce.png)

**Comment by ucl-borisw** [comment] 2019-07-25 08:00
Hello,

The problem may be cause by the version of bootstrap with bootbox.
I have found a quick fix : overwrite modal-header.

`.modal-header {
  display: block;
}`

**Comment by jma** [comment] 2019-07-29 06:49
> Hello,
> 
> The problem may be cause by the version of bootstrap with bootbox.
> I have found a quick fix : overwrite modal-header.
> 
> `.modal-header { display: block; }`

Hello thanks for your proposition. The problem is that the modal dialog is not well written and should be fixed as:
```html
      <div class="modal-header">
        <h5 class="modal-title" id="myModalLabel">{{ _('Confirm Delete') }}</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
```
I will propose a PR soon.

**Closed** 2019-08-26 06:58 UTC
Labels: minor
