### ISSUE TITLE
Display a warning when canceling in the editor

### ISSUE THREAD

**Issue by JoelleDosimont** [rero/rero-ils#2413] opened 2021-09-28 07:07 UTC
**How it works**

In the editor, when pressing the button "Cancel" the editor simply shuts down. If there was data filled in it, there is no way to go back to the editor and find those data again (for ex. in a new document record).

**Improvement suggestion**

When pressing the "Cancel" button a warning message is displayed: "Are you sure you want to cancel without saving the modifications ?" Yes / No.

**Comment by pronguen** [comment] 2021-11-25 16:11
Duplicate of #2104

**Closed by pronguen** 2021-11-25 16:11 UTC
Labels: enhancement, editor, professional ui, p-Low, UX
