### ISSUE TITLE
Some barcode searches giving too many results

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#2526] opened 2021-11-16 07:24 UTC
**Describe the bug**

This search gives 442 results in organisation `vs`:
https://bib.rero.ch/api/documents/?q=1012340829

In most of the results, it is impossible to find the string `1012340829`.

A barcode search in the items works fine.

**To Reproduce**

1. Launch the search indicated above

**Expected behavior**

For such a search, there should be in most of the case 1 hit, because the string is a barcode.

**Context**

* server: bib.rero.ch
* version: `v1.6.1`

[1]: https://ils.test.rero.ch
[2]: https://ilsdev.test.rero.ch

**Comment by jma** [comment] 2021-11-16 14:24
This can be reproduced on ilsdev or ilstest:
https://ilsdev.test.rero.ch/global/search/documents?q=10000002193&page=1&size=10
should not have too much results.

https://ilsdev.test.rero.ch/global/search/documents?q=holdings.items.barcode:10000002193&page=1&size=10&sort=bestmatch&simple=0 

This is because the global search consider also autocomplete fields. This should be fixed by adapting the es mapping with:
 "include_in_all" : false. See es doc for more details.

**Closed** 2021-11-25 09:08 UTC
Labels: search, bug, p-Medium
