### ISSUE TITLE
Help link on ilspilot refers to ils.test

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#1575] opened 2020-12-17 16:43 UTC
**Describe the bug**

The help link on the professional interface of ilspilot refers to ils.test.

**To Reproduce**

1. Log in as a librarian in ilspilot
2. Click on the help link

**Expected behavior**

It refers to ilspilot

**Context**

* ilspilot
* v 0.14.1

**Comment by iGormilhit** [comment] 2021-01-14 06:42
Seems to be fixed in `v0.15.0`. Can't reproduce it on https://ilsdev.test.rero.ch.

**Comment by iGormilhit** [comment] 2021-02-08 09:32
Fixed in the `v1.0.0` pre release.

**Closed by iGormilhit** 2021-02-08 09:32 UTC
Labels: P: Medium, bug, needs info, pilot libraries, professional ui
