### ISSUE TITLE
When placing a request on search results filtered by library, only selected libray should be listed

### ISSUE THREAD

**Issue by paprickka** [rero/rero-ils#2304] opened 2021-08-17 08:54 UTC
**How it works**
On  the public interface, one of the facets proposed for search results filtering is the library.
However, when you decide to place a request on the one of the search results, you see again all libraries listed.

**Improvement suggestion**
Ideally the filter on library should be transported to the request form so that only the library / libraries you selected are displayed.
In addition, to ease usage of the interface, libraries should always be listed in the same order

**Comment by iGormilhit** [comment] 2021-08-25 09:18
@paprickka Thanks for this issue.

The facets of the document result list filter the documents. With the library facet, the filter is based on information from the items (to identify the owning libraries), but still, the results are documents. Thus, when displaying a *document* all it's linked items appear.

This kind of "issue" are well known, but, at least on my understanding, there's no way to change that behavior.

**Comment by pronguen** [comment] 2022-03-15 12:47
Duplicate of https://github.com/rero/rero-ils/issues/2278

**Closed by pronguen** 2022-03-15 12:47 UTC
Labels: duplicate, enhancement, f: search, f: public ui
