### ISSUE TITLE
Editor: adding an element to a type array

### ISSUE THREAD

**Issue by Garfield-fr** [rero/rero-ils#3661] opened 2024-05-02 06:50 UTC
### Bug description:
In certain situations, when a new element is added, the next element is emptied of this data.

### Expected behavior:
When an element is added, it must be inserted into the list, but must not delete data from other elements.

### Steps to Reproduce:
1. Go to documents
2. Search "flamand" and edit the record
3. Jump to Subjects
4. Add a new entry by clicking on the first subject
5. The next subject after insertion no longer contains any data

### Context
- Versions: 1.22-dev version (Angular 17/ngx-formly 6)
- Browser: all

**Comment by PascalRepond** [comment] 2024-05-06 05:49
Duplicate of https://github.com/rero/rero-ils/issues/2625

**Closed** 2024-05-15 09:35 UTC
Labels: f: professional ui, bug, p-High
