### ISSUE TITLE
English seems to imply US English with US date formats

### ISSUE THREAD

**Issue by bertvandepoel** [rero/rero-ils#2672] opened 2022-01-30 13:07 UTC
My university switched from an old library system to RERO ILS this week. When I went to renew my loans, I noticed that the dates were unexpectedly in US format (so my loans expire on 2/18/22 after renewal, instead of 18/2/22 or something like 18 feb 2022). I'm not quite sure if this is a problem in RERO ILS or in my university's configuration.

**How it works**

When I visit the loans page on /patrons/profile, the page is in English by default (my browser's locale is en_uk, which presumably RERO gets through the Language header and then decides it should pick English). Strangely, this means that all the loan dates are shown in US date format, as you can see in the screenshot below.
![Screenshot at 2022-01-30 14-04-41](https://user-images.githubusercontent.com/4948317/151700909-8adef5c0-e7fd-47d6-aa9e-8663bff8d674.png)

In French however, the official language of my university (but which I haven't fully mastered myself), the date format looks normal:
![Screenshot at 2022-01-30 14-05-11](https://user-images.githubusercontent.com/4948317/151700939-d7d57b8f-44eb-493b-9aef-dcdb2fa4fcc3.png)

**Improvement suggestion**

I'm not sure whether an improvement is needed or whether this is caused by a configuration error by my university. If English always implies en_us within RERO ILS then obviously I would suggest that that is split up to also support en_uk or another en_ that uses a more common date format (or even the ISO format). However, if this is a configuration error then please let me know what information I can pass on to my university to either add 2 English options or to reconfigure English to not use US formats.

I'm not sure if this is the same issue as #1469, I wanted to comment about this there, but seem to be unable to because it was closed for being stale.

**Comment by pronguen** [comment] 2022-02-07 18:26
@Garfield-fr Could you confirm that we implemented the US date format (for the date in the public view) when the language is English?

**Comment by PascalRepond** [comment] 2022-03-18 08:34
After testing, I can confirm that using English as RERO-ILS language shows certain dates in US-format, regardless of any locale setting in the OS or browser. I re-opened #1469 and gave it a medium priority.

**Comment by PascalRepond** [comment] 2022-06-29 06:59
Closing this as a duplicate of #1469

**Closed by PascalRepond** 2022-06-29 06:59 UTC
Labels: enhancement, f: circulation, f: public ui, p-Medium
