### ISSUE TITLE
Search spinner in progress even after search is complete

### ISSUE THREAD

**Issue by BadrAly** [rero/rero-ils#1689] opened 2021-02-10 11:41 UTC
In the admin interface, if you place any search the spinner remain in progress even after switching to other pages.

**To Reproduce**

1. Go to admin interface and login as a librarian
2. on the search bar, place any keyword search
3. go the document detail view of any document
4. the spinner is still in-progress

* server: [ils.test.rero.ch][1]
* version: `v0.1.0.0` 

<img width="1219" alt="Screenshot 2021-02-10 at 12 40 34" src="https://user-images.githubusercontent.com/26998238/107505587-377e6580-6b9d-11eb-8e2d-11b7bfaa5a6c.png">

**Comment by pronguen** [comment] 2021-03-02 13:33
@BadrAly I couldn't reproduce this issue on the deployed v1.0.0. I think we can close it.

**Comment by BadrAly** [comment] 2021-03-02 13:34
@pronguen I agree

**Closed** 2021-03-02 13:34 UTC
Labels: P: Low, bug, professional ui, search
