### ISSUE TITLE
Uniformize data mapping in documents to account for local and linked agents (contributions, subjects)

### ISSUE THREAD

**Issue by zannkukai** [rero/rero-ils#2814] opened 2022-04-05 11:09 UTC
As a librarian, I need agents to have the similar ES mappings regardless of the field where they are used, so that I can more easily use facets and expert searches.

### Acceptance criteria

- The jsonschema for [document_subjects (Person(local))](https://github.com/rero/rero-ils/blob/staging/rero_ils/modules/documents/jsonschemas/documents/document_subjects-v0.0.1.json#L15-L77) contains all the fields as in [document_contribtion_person](https://github.com/rero/rero-ils/blob/staging/rero_ils/modules/documents/jsonschemas/documents/document_contribution_person-v0.0.1.json), plus the existing subfields specific to subject.
- The jsonschema for [document_subjects (Corporate Body (local))](https://github.com/rero/rero-ils/blob/staging/rero_ils/modules/documents/jsonschemas/documents/document_subjects-v0.0.1.json#L78-L149) contains all the fields as in [document_contribtion_organisation](https://github.com/rero/rero-ils/blob/staging/rero_ils/modules/documents/jsonschemas/documents/document_contribution_organisation-v0.0.1.json).
- The mapping for [`document.subjects`](https://github.com/rero/rero-ils/blob/staging/rero_ils/modules/documents/mappings/v7/documents/document-v0.0.1.json#L832-L911) also contains all the fields and follows the same logic as in the mapping for [`document.contributions.agent`](https://github.com/rero/rero-ils/blob/staging/rero_ils/modules/documents/mappings/v7/documents/document-v0.0.1.json#L832-L911)
    - `subject.preferred_name` is copied to `subject_facet` so that it is used in the subject facet

### Additional context 
The internationalization mechanism for the subjects facet (as in contribution facet) would be nice-to-have, it is out of scope of this US, unless it is low-effort.

**Comment by pronguen** [comment] 2022-04-19 10:36
Duplicate of #2609

**Comment by zannkukai** [comment] 2022-04-19 13:02
@pronguen, the rero/rero-ils#2609 describe 2 distinct behavior : one for ReferencedSubject (MEF), other one for LocalSubject.
The PR rero/rero-ils#2808 will solve the issue for LocalSubject BUT not for MEF subject. This is why I opened this issue (to keep in mind that MEF subject will not be indexed as expected).
If we close this issue now : 
  - either we need to edit the issue 2609 after PR#2808 merging.
  - either we lost this problem after merging PR#2808

**Closed** 2023-05-16 12:07 UTC
Labels: f: data, f: mef, correction
