### ISSUE TITLE
Problem with the first search of a document on the pro interface

### ISSUE THREAD

**Issue by JoelleDosimont** [rero/rero-ils#2652] opened 2022-01-25 11:19 UTC
**Describe the bug**

When switching to the pro interface, performing a search in the search box on the menu page -> the number of results obtain is too big. Seems to occur when the search contains more than one word. See screenshots
It's ok when you perform the search on the "document" page.

**To Reproduce**

1. Connect to the Pro interface
2. Perform a document search with at least 2 words (ex. : bulletin d'études)
3. See that the number of results is too big

**Expected behavior**

The results obtains with this first search should be the same as the next ones.

**Context**

* server: [ilsdev.test.rero.ch][2]
* version: rero-ils version ab4ebe55 -- rero-ils-ui version 66ed8903

[1]: https://ils.test.rero.ch
[2]: https://ilsdev.test.rero.ch

**Screenshots**

![image](https://user-images.githubusercontent.com/55576980/150966593-f6371cb8-b49d-4eb4-ad09-bef1b230e27b.png)

**Comment by pronguen** [comment] 2022-02-21 07:53
@JoelleDosimont I close it because I think it is a duplicate of #2562 (solved in version 1.9.0).

**Closed by pronguen** 2022-02-21 07:53 UTC
Labels: f: search, f: professional ui, class: bug, p-Low
