### ISSUE TITLE
Deleting a document should be possible when all order lines are marked as received

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#2689] opened 2022-02-08 15:41 UTC
**How it works**

Currently, it is not possible to delete a document when an order line is linked, whatever the status of the order line is.

**How it should works**

* It is possible to delete a document with order lines attached, but only if all the items ordered have been received (or cancelled).
* The display of the closed order line and receipt are not impacted by the deletion of the document

**Comment by PascalRepond** [comment] 2023-02-07 07:25
Duplicate of #3225

**Closed by PascalRepond** 2023-02-07 07:25 UTC
Labels: f: permissions, f: acquisitions, p-Medium, correction
