### ISSUE TITLE
Setting in the librarian profile to have a default filter on his.her organisation

### ISSUE THREAD

**Issue by pronguen** [rero/rero-ils#2286] opened 2021-08-11 07:11 UTC
**How it works**

Following the correction of https://github.com/rero/rero-ils/issues/2130, the document search of the professional interface
* via the main header is filtered by the login organisation;
* via the search input of the document search view is not filtered.

**Improvement suggestion**

* Both search behaves in the same manner (the user won't understand it otherwise)
* A setting in the librarian profile (patron resource) enable to choose to enable the filter or not
    * Cataloguing librarians might enable it where circulation librarians not

**Comment by PascalRepond** [comment] 2023-02-06 15:38
Duplicate of #2891

**Closed by PascalRepond** 2023-02-06 15:38 UTC
Labels: duplicate, enhancement, wontfix, f: search, f: professional ui, f: user management, p-Medium
