### ISSUE TITLE
Missing create button for the first record of a given resource

### ISSUE THREAD

**Issue by iGormilhit** [rero/rero-ils#541] opened 2019-10-01 11:41 UTC
**Describe the issue**
As the professional search view has no result to display, no record creation button is displayed. This situation should not be happening very often, but still, a way to create the very first record should exists, maybe as for documents (in the professional menu).

**To Reproduce**
1. Create an empty organisation.
1. Create a library into that organisation.
1. Create a system librarian attached to that library.
1. Log in as this system librarian.
1. Through the professional menu: Admin & Monitoring / Item types.
1. Get no result, see the "create" button which is missing.

**Expected behavior**
The librarian should have a way to create the first record of any resource type.

**Screenshots**
![empty-resource-no-create-button](https://user-images.githubusercontent.com/1557213/65958900-100f7880-e440-11e9-8795-86b86c324096.png)

**Additional context**
Maybe the PO group could provide specifications for this. This could be done during the professional views refactoring.

**Comment by AoNoOokami** [comment] 2020-02-25 13:04
I'm closing this issue because I can confirm that it is resolved with the new professional interface. ng-core implements this add button even in an empty view.

**Closed by AoNoOokami** 2020-02-25 13:04 UTC
Labels: professional ui, to be checked
