### ISSUE TITLE
User account (public): filter by institution

### ISSUE THREAD

**Issue by ManaDeweerdt** [rero/rero-ils#2615] opened 2021-12-21 12:04 UTC
**How it works**

For now, in the public interface, the user has to use the filter in order to see the loans from other institutions.
The order of the filter remains the same and can be problematic if the user is mainly affiliated to the 2nd or to the 3rd institution and needs to switch.

**Improvement suggestion**

1/ the filter changes depending on the institutional view.
or
2/ delete the filter and display all the loans at the same time. Add a sort: location, title, due date. Add a toggle 'collapse details'.

**Comment by pronguen** [comment] 2022-01-17 13:55
Duplicate of #2195

**Closed by pronguen** 2022-01-17 13:55 UTC
Labels: enhancement, f: public ui, triage, p-Medium
